In [3]:
import numpy as np

# Assign values for a,b,c,d

In [4]:
a=np.array ([10,20,30])
b=np.array ([[(40,50,60),
            (70,80,90)],
            [(20,35,85),
            (50,76,56)]])
c=np.array (['Luke'])
d=np.array ([2.56,2.5])
e=np.array(54)

# Print arrays 

In [5]:
print(a)
print(b)
print(c)
print(d)
print(e)

[10 20 30]
[[[40 50 60]
  [70 80 90]]

 [[20 35 85]
  [50 76 56]]]
['Luke']
[2.56 2.5 ]
54


# number of dimensions

In [6]:
print (b.ndim)

3


In [7]:
print(a.ndim)

1


In [8]:
print(e.ndim)

0


# print shapes

In [9]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)

(3,)
(2, 2, 3)
(1,)
(2,)
()


# Print data type

In [10]:
print (a.dtype)
print (b.dtype)
print (c.dtype)
print (d.dtype)
print (e.dtype)

int64
int64
<U4
float64
int64


# Example 2

In [11]:
f=np.array([[10,20,30],
            [40,50,60],
            [70,80,90]])

# Copy and Print previous array

In [12]:
g=np.copy(f)
print(g)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [13]:
g,f

(array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]),
 array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]))

In [14]:
h=g.view()
print(h)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [15]:
print('f:')
print(f)
print('g:')
print(g)

f:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
g:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


# Add, multiply, substract constants

In [16]:
g+5

array([[15, 25, 35],
       [45, 55, 65],
       [75, 85, 95]])

In [17]:
g*10

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [18]:
g-20.589

array([[-10.589,  -0.589,   9.411],
       [ 19.411,  29.411,  39.411],
       [ 49.411,  59.411,  69.411]])

In [19]:
g+f
print(g+f)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]


In [20]:
g[1:2]

array([[40, 50, 60]])

# sort array

In [21]:
a=np.array([10,50,18,90,40,65])

In [22]:
np.sort(a)

array([10, 18, 40, 50, 65, 90])

# Append

In [23]:
a=np.array([10,20]),([30,40])
b=np.array([50,60]),([70,80])

In [24]:
np.append(a,b).reshape(4,2)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [25]:
a

(array([10, 20]), [30, 40])

# Split

In [28]:
x =np.arange(10,110,10)


In [29]:
x


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [34]:
np.split(x,5)

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

In [35]:
np.split(x,2)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]

In [38]:
np.split(x,1)

[array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])]

In [40]:
z=np.split(x,5)
print(z)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([ 90, 100])]


In [43]:
print(x)
print(z)


[ 10  20  30  40  50  60  70  80  90 100]
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([ 90, 100])]


In [44]:
s1,s2,s3,s4,s5= np.split(x,5)

In [46]:
s1,s2,s3,s4,s5

(array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100]))

In [47]:
np.vstack((s1,s2,s3,s4,s5))

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [48]:
np.hstack((s1,s2,s3,s4,s5))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [50]:
np.hstack((s1,s2,s3,s4,s5))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [56]:
q=np.arange(10,150,10)


In [57]:
print(q)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140]


In [67]:
np.split(x,3/3)

[array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])]

In [78]:
a=np.arange(10,130,10).reshape(4,3)
print (a)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [81]:
np.where(a==100)

(array([3]), array([0]))

In [84]:
s=np.arange(10,190,5)
print(s)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185]


In [101]:
np.searchsorted(s,70)

np.int64(12)

In [105]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)

[11 22 33]


In [109]:
np.add(a,b)


array([11, 22, 33])

In [110]:
np.subtract(a,b)

array([ 9, 18, 27])

In [111]:
np.power(a,b)

array([   10,   400, 27000])

In [112]:
np.multiply(a,b)

array([10, 40, 90])

In [113]:
np.divide(a,b)

array([10., 10., 10.])